version: '2.3'

services:
  postgresql:
    image: postgres:9.6
    environment:
        POSTGRES_USER: hungvi
        TZ: Asia/Jakarta
    ports:
        - 5432:5432
    # volumes:
    #     - ./volumes/postgresql/data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U hungvi"]
        interval: 30s
        timeout: 30s
        retries: 3
    mem_limit: 500m
  
  kong-migrations:
    image: "${KONG_DOCKER_TAG:-kong:1.0.3}"
    command: kong migrations bootstrap
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: postgresql
      KONG_PG_PORT: 5432
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      KONG_PG_USER: ${KONG_PG_USER:-kong}
    links:
      - postgresql:postgresql

  api-gateway:
    image: api-gateway
    build:
      context: ./api-gateway
    ports:
      - 8000:8000
      - 8001:8001
    environment:
      KONG_PG_HOST: postgresql
      KONG_TRUSTED_IPS: 0.0.0.0/0
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 127.0.0.1:8444 ssl"
      ACCOUNT_DATABASE_HOST: postgresql
    depends_on:
      postgresql:
        condition: service_healthy

networks:
  default:
    external:
      name: test
