version: '2.3'

services:
  postgresql:
    image: postgres:9.6
    environment:
        POSTGRES_USER: vnext
        TZ: Asia/Jakarta
    ports:
        - 5432:5432
    # volumes:
    #     - ./volumes/postgresql/data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U vnext"]
        interval: 30s
        timeout: 30s
        retries: 3
    mem_limit: 500m

  api-gateway:
    image: api-gateway
    build:
      context: ./api-gateway
    ports:
      - 8000:8000
      - 8001:8001
    environment:
      KONG_PG_HOST: postgresql
      KONG_TRUSTED_IPS: 0.0.0.0/0
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 127.0.0.1:8444 ssl"
    depends_on:
      postgresql:
        condition: service_healthy

networks:
  default:
    external:
      name: test
